
KlikEventEventBundle:
    resource: "@KlikEventEventBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: KlikEventSecurityBundle:Security:login }

login_check:
    pattern:   /login_check

KlikEventEventBundle_EventAdmin:
    resource: "@KlikEventEventBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

KlikEventEventBundle_CategoryAdmin:
    resource: "@KlikEventEventBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
