KlikEventAdminBundle_admin_klik_event_admin_bundle_admin:
    resource: "@KlikEventAdminBundle/Controller/Admin/"
    type:     admingenerator
    prefix:   /admin/klik_event_admin_bundle/admin

KlikEventEventBundle:
    resource: "@KlikEventEventBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
