KlikEventEventBundle_homepage:
    pattern:  /
    defaults: { _controller: KlikEventEventBundle:Default:index, name: Index }


KlikEventEventBundle_HotEvent_page:
    pattern:  /hot
    defaults: { _controller: KlikEventEventBundle:Default:showHot }


KlikEventEventBundle_TodayEvent_page:
    pattern:  /today
    defaults: { _controller: KlikEventEventBundle:Default:showEventByDate, name: Today }

KlikEventEventBundle_Tips_page:
    pattern:  /tips
    defaults: { _controller: KlikEventEventBundle:Default:template, name: Tips }

# SUBSCRIBE PATHS START
KlikEventEventBundle_Subscribe_page:
    pattern:  /subscribe
    defaults: { _controller: KlikEventEventBundle:Default:subscribe, name: Subscribe }
#SUBSCRIBE PATHS END

KlikEventEventBundle_EventsByCategory_page:
    pattern:  /event/category/{category}
    defaults: { _controller: KlikEventEventBundle:Default:template, name: EventsByCategory }
    requirements:
        month: "[a-zA-Z]+"

KlikEventEventBundle_eventsByDate_page:
    pattern:  /event/{date}/{month}/{year}
    defaults: { _controller: KlikEventEventBundle:Default:showEventByDate, name: EventsByDate }
    requirements:
        date:  "[0-9]{1,2}"
        month: "[0-9]{1,2}"
        year:  "[0-9]{4}"

KlikEventEventBundle_eventsByMonth_page:
    pattern:  /event/{month}/{year}
    defaults: { _controller: KlikEventEventBundle:Default:template, name: EventsByMonth }
    requirements:
        month: "[0-9]{1,2}"
        year:  "[0-9]{4}"

KlikEventEventBundle_eventsByYear_page:
    pattern:  /event/{year}
    defaults: { _controller: KlikEventEventBundle:Default:template, name: EventsByYear }
    requirements:
        year:  "[0-9]{4}" 

KlikEventEventBundle_eventDetails_page:
    pattern:  /event/id/{id}
    defaults: { _controller: KlikEventEventBundle:Default:template, name: EventsDetailsID }
    requirements:
        id:  "[0-9]+" 