KlikEventEventBundle_homepage:
    pattern:  /
    defaults: { _controller: KlikEventEventBundle:Default:showHot }


KlikEventEventBundle_HotEvent_page:
    pattern:  /hot
    defaults: { _controller: KlikEventEventBundle:Default:showHot }


KlikEventEventBundle_TodayEvent_page:
    pattern:  /today
    defaults: { _controller: KlikEventEventBundle:Default:showEventByDate }

KlikEventEventBundle_Tips_page:
    pattern:  /tips
    defaults: { _controller: KlikEventEventBundle:Default:defaultTips }

KlikEventEventBundle_Feedback_page:
    pattern:  /feedback
    defaults: { _controller: KlikEventEventBundle:Default:defaultFeedback}

KlikEventEventBundle_TipsEventOwner_page:
    pattern:  /tips_event_owner
    defaults: { _controller: KlikEventEventBundle:Default:defaultTipsEventOwner}


KlikEventEventBundle_Subscribe_page:
    pattern:  /subscribe
    defaults: { _controller: KlikEventEventBundle:Default:subscribe }


KlikEventEventBundle_EventsByCategory_page:
    pattern:  /event/category/{category}
    defaults: { _controller: KlikEventEventBundle:Default:showEventByCategory}
    requirements:
        month: "[a-zA-Z]+"

KlikEventEventBundle_eventsByDate_page:
    pattern:  /event/{date}/{month}/{year}
    defaults: { _controller: KlikEventEventBundle:Default:showEventByDate }
    requirements:
        date:  "[0-9]{1,2}"
        month: "[0-9]{1,2}"
        year:  "[0-9]{4}"

KlikEventEventBundle_eventDetails_page:
    pattern:  /event/id/{id}
    defaults: { _controller: KlikEventEventBundle:Default:showEventDetails}
    requirements:
        id:  "[0-9]+" 