# KlikEvent/EventBundle/Resources/config/validation.yml
KlikEvent\EventBundle\Entity\Subscriber:
    properties:
        email:
            - NotBlank: ~
            - Email: ~

KlikEvent\EventBundle\Entity\Feedback:
    properties:
        content:
            - NotBlank: ~
        fromEmail:
            - Email: ~

