# KlikEvent/EventBundle/Resources/config/validation.yml
KlikEvent\EventBundle\Entity\Subscriber:
    properties:
        email:
            - NotBlank: ~
            - Email: ~

KlikEvent\EventBundle\Entity\Feedback:
    properties:
        content:
            - NotBlank: ~
        fromEmail:
            - Email: ~

KlikEvent\EventBundle\Entity\Event:
    properties:
        eventTitle:
            - NotBlank: ~
        eventLocation1:
            - NotBlank: ~
        eventShortDescription:
            - NotBlank: ~
        eventDescription:
            - NotBlank: ~
        eventCategories:
            - NotBlank: ~
        eventCoverImage:
            - Image: ~


